# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 08:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_name', models.CharField(max_length=15)),
                ('landing_pic', models.ImageField(upload_to='profile-pic/')),
                ('room_one', models.ImageField(upload_to='profile-pic/')),
                ('room_two', models.ImageField(upload_to='profile-pic/')),
                ('room_three', models.ImageField(upload_to='profile-pic/')),
                ('room_four', models.ImageField(upload_to='profile-pic/')),
                ('room_five', models.ImageField(upload_to='profile-pic/')),
                ('roomsix', models.ImageField(upload_to='profile-pic/')),
                ('room_seven', models.ImageField(upload_to='profile-pic/')),
                ('room_eigth', models.ImageField(upload_to='profile-pic/')),
                ('room_nine', models.ImageField(upload_to='profile-pic/')),
                ('room_ten', models.ImageField(upload_to='profile-pic/')),
                ('room_eleven', models.ImageField(upload_to='profile-pic/')),
                ('room_twelve', models.ImageField(upload_to='profile-pic/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Landlord_tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile-pic/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
