# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ImageField(upload_to='profile-pic/')),
            ],
        ),
        migrations.RemoveField(
            model_name='house',
            name='room_eigth',
        ),
        migrations.RemoveField(
            model_name='house',
            name='room_eleven',
        ),
        migrations.RemoveField(
            model_name='house',
            name='room_five',
        ),
        migrations.RemoveField(
            model_name='house',
            name='room_four',
        ),
        migrations.RemoveField(
            model_name='house',
            name='room_nine',
        ),
        migrations.RemoveField(
            model_name='house',
            name='room_one',
        ),
        migrations.RemoveField(
            model_name='house',
            name='room_seven',
        ),
        migrations.RemoveField(
            model_name='house',
            name='room_ten',
        ),
        migrations.RemoveField(
            model_name='house',
            name='room_three',
        ),
        migrations.RemoveField(
            model_name='house',
            name='room_twelve',
        ),
        migrations.RemoveField(
            model_name='house',
            name='room_two',
        ),
        migrations.RemoveField(
            model_name='house',
            name='roomsix',
        ),
        migrations.AddField(
            model_name='room',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.House'),
        ),
    ]
