# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_auto_20171214_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
